<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0');
        \Illuminate\Support\Facades\DB::table('products')->truncate();
        \Illuminate\Support\Facades\DB::table('products')->insert([
            [
                'name'=> '#1',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#2',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>150000,
                'description'=>'Nick Bạc đoàn',
                'detail'=>'140 tướng, 115 trang phục',
            ],
            [
                'name'=> '#3',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick Bạc Đoàn',
                'detail'=>'123 tướng, 23 trang phục',
            ],
            [
                'name'=> '#4',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>550000,
                'description'=>'Nick Bạch Kim Đoàn',
                'detail'=>'140 tướng, 76 trang phục',
            ],
            [
                'name'=> '#5',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>30000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Tướng 100, trang phục 5',
            ],
            [
                'name'=> '#6',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick Bạch kim đoàn',
                'detail'=>'140 tướng, 55 trang phục',
            ],
            [
                'name'=> '#7',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'140 tướng, 15 trang phục',
            ],
            [
                'name'=> '#8',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>110000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'119 tướng, 20 trang phục',
            ],
            [
                'name'=> '#9',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>80000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'90 tướng, 10 trang phục',
            ],
            [
                'name'=> '#10',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>200000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc',
            ],
            [
                'name'=> '#11',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>210000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc',
            ],
            [
                'name'=> '#12',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>240000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc, có thêm 3 game steam',
            ],
            [
                'name'=> '#13',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>230000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc, có thêm game For Honor',
            ],
            [
                'name'=> '#14',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>300000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc, có thêm game CSGO',
            ],
            [
                'name'=> '#15',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#16',
                'categoryId'=>7,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc, có thêm 30 game, đã chơi 3 năm',
            ],
            [
                'name'=> '#17',
                'categoryId'=>8,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>120000,
                'description'=>'Nick CSGO Silver 1',
                'detail'=>'Nick mới tạo, full email gốc',
            ],
            [
                'name'=> '#18',
                'categoryId'=>8,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick CSGO Silver 3',
                'detail'=>'Nick full email gốc, đã mở steam market, có Dragon Lore',
            ],
            [
                'name'=> '#19',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>250000,
                'description'=>'Nick CSGO Silver Elite',
                'detail'=>'Nick full email gốc, có 10 skins',
            ],
            [
                'name'=> '#20',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick CSGO Gold Novas 2',
                'detail'=>'Nick tạo được 3 tháng, full email gốc, ko có skin',
            ],
            [
                'name'=> '#21',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>450000,
                'description'=>'Nick CSGO Gold Novas Master',
                'detail'=>'Nick full email gốc, có 30 skins, có thêm 2 game steam',
            ],
            [
                'name'=> '#22',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>220000,
                'description'=>'Nick CSGO Gold Novas 1',
                'detail'=>'Nick tạo được 6 tháng, full email gốc, ko có skin, có 5 game steam',
            ],
            [
                'name'=> '#23',
                'categoryId'=>10,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>350000,
                'description'=>'Nick CSGO Master Guardian Elite',
                'detail'=>'Nick dùng được 2 năm, đã mở steam market, full email gốc, có skin team VP',
            ],
            [
                'name'=> '#24',
                'categoryId'=>10,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>550000,
                'description'=>'Nick CSGO Master Guardian 1',
                'detail'=>'Nick dùng được 3 năm, đã mở steam market, full email gốc, có skin team Navi, có 10 game steam',
            ],
            [
                'name'=> '#25',
                'categoryId'=>10,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>3000000,
                'description'=>'Nick CSGO Master Guardian 2',
                'detail'=>'Nickđã mở steam market, full email gốc, có ButterFly Faded, có 20 game steam',
            ],
            [
                'name'=> '#26',
                'categoryId'=>11,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>700000,
                'description'=>'Nick CSGO Legendary Eagle',
                'detail'=>'Nick dùng được 4 năm, đã mở steam market, full email gốc, có skin team VP, Navi, Astralis, có 4 game steam',
            ],
            [
                'name'=> '#27',
                'categoryId'=>11,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>1000000,
                'description'=>'Nick CSGO Legendary Eagle Master',
                'detail'=>'Nick đã mở steam market, full email gốc, có 6 game steam, có full skin súng cơ bản',
            ],
            [
                'name'=> '#28',
                'categoryId'=>12,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>1400000,
                'description'=>'Nick CSGO Supreme Master',
                'detail'=>'Nick đã mở steam market, full email gốc, có skin team Nip, SK, Astralis, có 8 game steam',
            ],
            [
                'name'=> '#29',
                'categoryId'=>12,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>2200000,
                'description'=>'Nick CSGO Supreme Master',
                'detail'=>'Nick đã mở steam market, full email gốc, có full skin các team, có full skin súng cơ bản và 2 dao xịn, có 18 game steam',
            ],
            [
                'name'=> '#30',
                'categoryId'=>13,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>3150000,
                'description'=>'Nick CSGO Global Elite',
                'detail'=>'Nick đã mở steam market, full email gốc, hòm có 120 item, hợp cho gosu nào thích go pro',
            ],
            [
                'name'=> '#31',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>3900000,
                'description'=>'Nick CSGO Global Elite',
                'detail'=>'Nick đã mở steam market, full email gốc, full skin súng và skin của Navi, có chữ ký của gosu S1mple, thích hợp cho fanboy chui hang',
            ],

        ]);
    }
}
