<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0');
        \Illuminate\Support\Facades\DB::table('products')->truncate();
        \Illuminate\Support\Facades\DB::table('products')->insert([
            [
                'name'=> '#1',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'45 tướng 11 trang phục',
            ],
            [
                'name'=> '#2',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>70000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'47 tướng 10 trang phục',
            ],
            [
                'name'=> '#3',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>70000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'30 tướng 11 trang phục',
            ],
            [
                'name'=> '#4',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>120000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'55 tướng 13 trang phục',
            ],
            [
                'name'=> '#5',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>200000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'28 tướng 8 trang phục',
            ],
            [
                'name'=> '#6',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'49 tướng 8 trang phục',
            ],
            [
                'name'=> '#7',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>70000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'35 tướng 10 trang phục',
            ],
            [
                'name'=> '#8',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>70000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'40 tướng 12 trang phục',
            ],
            [
                'name'=> '#9',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>150000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'66 tướng 13 trang phục',
            ],
            [
                'name'=> '#10',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>120000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'41 tướng 5 trang phục',
            ],
            [
                'name'=> '#11',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>70000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'23 tướng 3 trang phục',
            ],
            [
                'name'=> '#12',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>40000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'23 tướng 6 trang phục',
            ],
            [
                'name'=> '#13',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>1700000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng 140 trang phục',
            ],
            [
                'name'=> '#14',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>1000000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng 88 trang phục',
            ],
            [
                'name'=> '#15',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>1000000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng 74 trang phục',
            ],
            [
                'name'=> '#16',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>1000000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng 75 trang phục',
            ],
            [
                'name'=> '#17',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>1200000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng 100 trang phục',
            ],
            [
                'name'=> '#18',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>800000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'11 tướng chưa sở hữu 40 trang phục',
            ],
            [
                'name'=> '#19',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick trống không có item, skin, full email gốc, có thêm 10 game, đã chơi 3 năm',
            ],
            [
                'name'=> '#20',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick có item, skin, full email gốc, có thêm 4 game, đã chơi 2 năm',
            ],
            [
                'name'=> '#21',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>250000,
                'description'=>'Nick PUBG Steam',
                'detail'=>'Nick có item, skin, full email gốc, có thêm 8 game, đã chơi 2 năm',
            ],
            [
                'name'=> '#22',
                'categoryId'=>8,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>250000,
                'description'=>'Nick CSGO Silver Elite',
                'detail'=>'Nick full email gốc, có 10 skins',
            ],
            [
                'name'=> '#23',
                'categoryId'=>9,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>150000,
                'description'=>'Nick CSGO Gold Novas 2',
                'detail'=>'Nick tạo được 3 tháng, full email gốc, ko có skin',
            ],
            [
                'name'=> '#24',
                'categoryId'=>9,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>450000,
                'description'=>'Nick CSGO Gold Novas Master',
                'detail'=>'Nick full email gốc, có 30 skins, có thêm 2 game steam',
            ],
            [
                'name'=> '#25',
                'categoryId'=>9,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>220000,
                'description'=>'Nick CSGO Gold Novas 1',
                'detail'=>'Nick tạo được 6 tháng, full email gốc, ko có skin, có 5 game steam',
            ],
            [
                'name'=> '#26',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>350000,
                'description'=>'Nick CSGO Master Guardian Elite',
                'detail'=>'Nick dùng được 2 năm, đã mở steam market, full email gốc, có skin team VP',
            ],
            [
                'name'=> '#27',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>550000,
                'description'=>'Nick CSGO Master Guardian 1',
                'detail'=>'Nick dùng được 3 năm, đã mở steam market, full email gốc, có skin team Navi, có 10 game steam',
            ],
            [
                'name'=> '#28',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>3000000,
                'description'=>'Nick CSGO Master Guardian 2',
                'detail'=>'Nickđã mở steam market, full email gốc, có ButterFly Faded, có 20 game steam',
            ],
            [
                'name'=> '#29',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>700000,
                'description'=>'Nick CSGO Legendary Eagle',
                'detail'=>'Nick dùng được 4 năm, đã mở steam market, full email gốc, có skin team VP, Navi, Astralis, có 4 game steam',
            ],
            [
                'name'=> '#30',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>1000000,
                'description'=>'Nick CSGO Legendary Eagle Master',
                'detail'=>'Nick đã mở steam market, full email gốc, có 6 game steam, có full skin súng cơ bản',
            ],
            [
                'name'=> '#31',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>1400000,
                'description'=>'Nick CSGO Supreme Master',
                'detail'=>'Nick đã mở steam market, full email gốc, có skin team Nip, SK, Astralis, có 8 game steam',
            ],
            [
                'name'=> '#32',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>2200000,
                'description'=>'Nick CSGO Supreme Master',
                'detail'=>'Nick đã mở steam market, full email gốc, có full skin các team, có full skin súng cơ bản và 2 dao xịn, có 18 game steam',
            ],
            [
                'name'=> '#33',
                'categoryId'=>13,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>3150000,
                'description'=>'Nick CSGO Global Elite',
                'detail'=>'Nick đã mở steam market, full email gốc, hòm có 120 item, hợp cho gosu nào thích go pro',
            ],
            [
                'name'=> '#34',
                'categoryId'=>9,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>3900000,
                'description'=>'Nick CSGO Global Elite',
                'detail'=>'Nick đã mở steam market, full email gốc, full skin súng và skin của Navi, có chữ ký của gosu S1mple, thích hợp cho fanboy chui hang',
            ],
            [
                'name'=> '#35',
                'categoryId'=>14,
                'thumbnail'=>'http://www.qygjxz.com/data/out/158/5223386-minecraft-wallpaper.jpg',
                'price'=>10000,
                'description'=>'Acc thường',
                'detail'=>'Không đổi được tên, skin, pass. Không có bảo hành. Có thể bị ban, dễ mất, không nên chơi lâu dài',
            ],
            [
                'name'=> '#36',
                'categoryId'=>14,
                'thumbnail'=>'http://www.qygjxz.com/data/out/158/5223386-minecraft-wallpaper.jpg',
                'price'=>150000,
                'description'=>'Acc unmigrated',
                'detail'=>'Đổi được tất cả bao gồm: tên, skin, pass, email. Đảm bảo vào được các Server bản quyền, không bị ban',
            ],
            [
                'name'=> '#37',
                'categoryId'=>14,
                'thumbnail'=>'http://www.qygjxz.com/data/out/158/5223386-minecraft-wallpaper.jpg',
                'price'=>200000,
                'description'=>'Acc full',
                'detail'=>'Đổi được tất cả thông tin',
            ],
            [
                'name'=> '#38',
                'categoryId'=>14,
                'thumbnail'=>'http://www.qygjxz.com/data/out/158/5223386-minecraft-wallpaper.jpg',
                'price'=>250000,
                'description'=>'Acc Cape Optifine',
                'detail'=>'Bạn sẽ nhận được 1 tài khoản có Optifine Cape. Bạn phải di chuyển CAPE sang acc chính của bạn ngay trong ngày.',
            ],
            [
                'name'=> '#39',
                'categoryId'=>14,
                'thumbnail'=>'http://www.qygjxz.com/data/out/158/5223386-minecraft-wallpaper.jpg',
                'price'=>120000,
                'description'=>'Acc semi full',
                'detail'=>'Đổi được: tên, skin, pass. Đảm bảo vào được các Server bản quyền, không bị ban.',
            ],
        ]);
    }
}
