<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0');
        \Illuminate\Support\Facades\DB::table('products')->truncate();
        \Illuminate\Support\Facades\DB::table('products')->insert([
            [
                'name'=> '#1',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#2',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#3',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#4',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#5',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#6',
                'categoryId'=>4,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>20000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#7',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#8',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#9',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#10',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#11',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#12',
                'categoryId'=>5,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>100000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#13',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#14',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#15',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#16',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#17',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#18',
                'categoryId'=>6,
                'thumbnail'=>'http://news.cdn.leagueoflegends.com/public/images/misc/Background.jpg',
                'price'=>500000,
                'description'=>'Nick bạch kim đoàn',
                'detail'=>'Full tướng ko skin',
            ],
            [
                'name'=> '#19',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#20',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#21',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#22',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#23',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#24',
                'categoryId'=>7,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>150000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#25',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#26',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#27',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#28',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#29',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#30',
                'categoryId'=>8,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>300000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#31',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#32',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#33',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#34',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#35',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#36',
                'categoryId'=>9,
                'thumbnail'=>'https://steamuserimages-a.akamaihd.net/ugc/931554217225615451/A0282B56D929E82A7F511E134C67815E8C7F6C56/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C637%3A358&composite-to=*,*%7C637%3A358&background-color=black',
                'price'=>500000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#37',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>10000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#38',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>10000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#39',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>10000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#40',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>10000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#41',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>10000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#42',
                'categoryId'=>10,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>10000,
                'description'=>'Nick đồng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#43',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#44',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#45',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#46',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#47',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#48',
                'categoryId'=>11,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick bạc đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#49',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#50',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#51',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#52',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#53',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
            [
                'name'=> '#54',
                'categoryId'=>12,
                'thumbnail'=>'https://vignette.wikia.nocookie.net/counterstrike/images/2/2f/Steam_Store_Global_Offensive_header_2015.jpg/revision/latest?cb=20150511180147&path-prefix=tr',
                'price'=>50000,
                'description'=>'Nick vàng đoàn',
                'detail'=>'Full đồ',
            ],
        ]);
    }
}
